### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by vikanezrimaya** [HalosGhost/shaman#35]
Hello! I have installed shaman and can't use it. When I launch it with any location (even really incorrect) it gives me: "shaman: No such file or directory" error. Any argument set without -l $something gives help message.

**Comment by HalosGhost** [comment]
Interesting. What happens if you manually specify the location of the cache file to use?

**Comment by kisik21** [comment]
Yeah! Found a problem!
You need to create cache file yourself. Then program will give you weather conditions.
    [kisik21@archlinux ~]$ touch $HOME/.shaman/$SCALE.json # $SCALE == imperial | metric
After this, will work on my machine.
Why shaman does not do this automatically? Is it some kind of UNIX way I didn't heard of?
________________________________

**Comment by HalosGhost** [comment]
Actually, ``shaman`` _should_ be doing that for you… Is ``$HOME`` defined oddly? Do you have ``$XDG_CONFIG_HOME`` defined? If so, what is it defined to be?

**Comment by kisik21** [comment]
Seems like $XDG_CONFIG_HOME isn't defined. Should it be? I do not use it normally, vast majority of CLI programs happily work without it. Maybe it will be defined when I login to GNOME or KDE. Who knows?

$HOME is default for Arch, /home/$USERNAME. And my username is same as on GitHub, kisik21. So it gives /home/kisik21 as my home dir.
________________________________

**Comment by HalosGhost** [comment]
No, ``XDG_CONFIG_HOME`` should not need to be defined (though ``shaman`` looks for it first before falling back), and that does look like a perfectly fine ``HOME`` value as well. I am not quite sure what is causing this. I will take some time to look through the cache-location code and see if I cannot determine what I did wrong.

**Comment by kisik21** [comment]
There is definitely something strange here. Anyway, thanks for help!
________________________________

**Comment by HalosGhost** [comment]
Can you do me a favor and post the full output you were getting with the error?

**Comment by kisik21** [comment]
Sorry, the error in title is full output.
________________________________

**Comment by HalosGhost** [comment]
@kisik21, that just cannot be the whole message. It must say something more; E.g., it might just precede the error message with ``shaman: ``, or it might say something else, but the full, unabridged output will help me narrow down where in the code I should start.

**Comment by kisik21** [comment]
It precedes the output with "shaman:".
________________________________

**Comment by HalosGhost** [comment]
Thanks!

**Comment by HalosGhost** [comment]
Okay, I believe I have this fixed (note that this bug never happened for me so I cannot be sure).

Please pull the latest, rebuild and give it a shot; let me know if that did not solve it for you.

**Comment by HalosGhost** [comment]
@kisik21, ping; did the update fix the issue you were having?

**Comment by kisik21** [comment]
Pong! Fixed!
Note for Arch users - you will need to resync shaman-git manually with
    $AUR_helper -S shaman-git
for fix to work.
________________________________

**Comment by kisik21** [comment]
Update: it now writes: "shaman: File exists".
Do I need to create new issue?
________________________________

**Comment by HalosGhost** [comment]
Oh, nope; that one is my fault too! Quick fix though!

Pushed. Let me know if that still runs into issues.

**Comment by kisik21** [comment]
That works as it should. Thank you very much for help!

**Comment by HalosGhost** [comment]
Happy to do it! Glad I got it functional for you!
